name: Release

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Release version'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      description:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Release description'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build packages
        run: |
          sudo apt install libasound2-dev -y
          make build-release
          make assembly-release-packages

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: build/release/package

  release:

    runs-on: ubuntu-latest

    needs: build

    permissions:
      contents: write

    steps:

    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: packages
        path: build/release/package

    - name: Release on Github
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ inputs.version }}
        tag_name: ${{ inputs.version }}
        body: ${{ inputs.description }}
        make_latest: true
        files: |
          ./build/release/package/yell-win-x64.zip
          ./build/release/package/yell-win-x86.zip
          ./build/release/package/yell-macos-intel-x64.zip
          ./build/release/package/yell-macos-silicon-arm64.zip
          ./build/release/package/yell-linux-x64.zip

  deploy-github-pages:
    name: Deploy to Github Pages
    uses: ./.github/workflows/deploy-docs.yml
